### ISSUE TITLE
Remove publishDir in config 

### ISSUE THREAD

**Issue by hcpss-mbarger** [HCPSS/api.hcpss.org#1]
I'd recommend removing the `publishDir` directive in config.  Hugo will then output to its default `public` directory freeing up the `docs` directory for any future application documentation.

**Comment by hcpss-banderson** [comment]
I would, but this way we can serve the site through github pages. This gives us the correct application/json header.

**Comment by hcpss-banderson** [comment]
For example:

https://hcpss.github.io/api.hcpss.org/schools/thes.json

**Comment by hcpss-mbarger** [comment]
I'm not sure we should host this through GitHub Pages. Yes, it is nice to have the free, scalable hosting but I was planning to add a robots.txt to the site so the data doesn't get picked up by Google and other external search engines.

Since this is a simple static site, I think we host this similar to StoryStrong on the apps server.

**Comment by hcpss-banderson** [comment]
Yes! Thats much better.
