### ISSUE TITLE
Add proper case initialism

### ISSUE THREAD

**Issue by nickadam** [HCPSS/api.hcpss.org#14]
Just a feature request to add proper case initialism somewhere so I don't have to maintain it elsewhere. For example:

- waves = WavES
- wates = WatES
- hohs = HoHS

**Comment by hcpss-banderson** [comment]
Great idea! Do you have a list? We don't use those in communications and I wonder if there are dependencies between those and the ones we use.

**Comment by nickadam** [comment]
I filtered by acronym less than 3 chars, then name doesn't have a space, these are the special ones. Cradlerock could be in contention. CRES? CrES? I Don't know. 
```
lower upper mine  Name
----- ----- ----  ----
cres  CRES  CrES  Cradlerock
hahs  HAHS  HaHS  Hammond
hohs  HOHS  HoHS  Howard
loes  LOES  LoES  Longfellow
wates WATES WatES Waterloo
waves WAVES WavES Waverly
```

**Comment by hcpss-mbarger** [comment]
Cradlerock is one word so it should be CrES like you are suggesting.

I would add Worthington to your list to make it seven total. Jenny Elam once told me that the school used WoES in their school communications.

	lower upper mine  Name
	----- ----- ----  ----
	cres  CRES  CrES  Cradlerock
	hahs  HAHS  HaHS  Hammond
	hohs  HOHS  HoHS  Howard
	loes  LOES  LoES  Longfellow
	wates WATES WatES Waterloo
	waves WAVES WavES Waverly
	woes  WOES  WoES  Worthington

**Comment by nickadam** [comment]
@hcpss-mbarger isn't Worthington WES?

**Comment by hcpss-banderson** [comment]
I agree on CrES, but we use wes not woes.

**Comment by hcpss-mbarger** [comment]
Originally, that is what I used for the subdomain since I thought the abbreviation was unfortunate. When Jenny was coordinator of Multimedia Communications, she had me change it to WoES since that was is what the school used. That is why their Twitter handle is `hcpss_woes`. The plan is to change the subdomain to woes.hcpss.org when it makes sense (design refresh, etc.) so the domain change can be timed with similar communication to their families.

I would keep it as WoES.

**Comment by hcpss-banderson** [comment]
oh, I thought we were moving from woes to wes and we were just untangling ourselves from woes.

**Comment by hcpss-banderson** [comment]
I am calling this thing an _abbreviation_ and I have added the case to the acronym so that this YAML:

```yaml
acronym: WavES
```

Will output JSON:

```json
{
  "acronym": "waves",
  "abbreviation": "WavES"
}
```

And

```yaml
acronym: WES
abbreviation: WoES
```

Will output:

```json
{
  "acronym": "wes",
  "abbreviation": "WoES"
}
```

**Comment by hcpss-banderson** [comment]
If @nickadam us OK with WoES, I will merge and deploy this.
