### ISSUE TITLE
How should we handle error states?

### ISSUE THREAD

**Issue by hcpss-mbarger** [HCPSS/api.hcpss.org#6]
While the API isn't currently dynamic, should we still handle a 404 error state instead of letting nginx serve the default 404 page?

Perhaps we should have the 404 return JSON as well.  Here is the XML response S3 sends with a 404:

```xml
<Error>
  <Code>AccessDenied</Code>
  <Message>Access Denied</Message>
  <RequestId><< unique token id >></RequestId>
  <HostId><< unique token id >></HostId>
</Error>
```

Perhaps something similar but in JSON:

```javascript
{
  "error": {
     "code": "404",
     "status": "Resource not available"
  }
}
```

**Comment by hcpss-mbarger** [comment]
My initial thinking is that this can be a singular JSON file in the `static` directory while nginx is configured to return this document for 404s.

**Comment by hcpss-banderson** [comment]
I agree. I think you should change "status" to "message" though.

**Comment by hcpss-mbarger** [comment]
Oops, that was a typo on my part. Definitely should be "message".
